export const animeGenres: {name: string}[] = [
                    {name: "Romance"}, 
                    {name: "Comedy"}, 
                    {name: "Drama"},
                    {name: "Ecchi"},
                    {name: "Adventure"},
                    {name: "Fantacy"},
                    {name: "Isekai"},
                    {name: "School"},
                    {name: "Sci-Fi"},
                    {name: "Game"},
                    {name: "Superpower"},
                    {name: "Shounen"},
                    {name: "Harem"},
                    {name: "Mecha"},
                    {name: "Supernatural"},
                    {name: "Action"},
                    {name: "Slice of Life"},
                    {name: "Seinen"},
                    {name: "Magic"},
                    {name: "Music"},
                    {name: "Shoujo"},
                    {name: "Psychological"},
                    {name: "Sports"},
                    {name: "Police"},
                    {name: "Josei"},
                    {name: "Magical Girl"},
                    {name: "Thriller"},
                    ]